version: 2
updates:
  - commit-message:
      prefix: "chore"
    directory: /support/modules-artifact-gen/tests/
    package-ecosystem: pip
    schedule:
      interval: weekly
  - commit-message:
      prefix: "chore"
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: monthly
